services:
  postgresql:
    image: 'postgres:15.4-alpine'
    environment:
      - 'POSTGRES_DB=maindb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=root'
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
